name = "PyramidScheme"
uuid = "ec211b67-1c2c-4319-878f-eaee078ee145"
version = "0.1.3"
authors = ["Felix Cremer <fcremer@bgc-jena.mpg.de> and contributors"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DiskArrayEngine = "2d4b2e14-ccd6-4284-b8b0-2378ace7c126"
DiskArrayTools = "fcd2136c-9f69-4db6-97e5-f31981721d63"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flatten = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAXArrayBase = "90b8fcef-0c2d-428d-9c56-5f86629e9d14"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"

[weakdeps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
PyramidSchemeArchGDALExt = "ArchGDAL"
PyramidSchemeMakieExt = "Makie"

[compat]
Aqua = "0.8"
ArchGDAL = "0.10.4"
CairoMakie = "0.13, 0.14, 0.15"
Colors = "0.12, 0.13"
DimensionalData = "0.28, 0.29"
DiskArrayEngine = "0.1.2, 0.2, 0.3"
DiskArrayTools = "0.1.10"
DiskArrays = "0.4.2"
Extents = "0.1.3"
FillArrays = "1.11"
Flatten = "0.4.3"
GeoInterface = "1.3.4"
Makie = "0.24.7"
OffsetArrays = "1.14"
Proj = "1.7.1"
Rasters = "0.11.8, 0.12, 0.13, 0.14"
Statistics = "1.10"
Test = "1.10"
TestItemRunner = "1"
YAXArrayBase = "0.6.1, 0.7"
YAXArrays = "0.5.6, 0.6, 0.7"
Zarr = "0.9.3"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
YAXArrayBase = "90b8fcef-0c2d-428d-9c56-5f86629e9d14"

[targets]
test = ["Aqua", "ArchGDAL", "Colors", "Extents", "CairoMakie", "Rasters", "Statistics", "Test", "TestItemRunner", "YAXArrayBase"]
